# Data Understanding

## Data Scientist Job Market Analysis

This notebook focuses on understanding the dataset structure, data quality and initial characteristics of job postings in the data science field.

The main objectives of this stage are:

- Understanding the dataset structure
- Inspect columns and data types
- Identify missing values and duplicate records
- Explore the main variables
- Define initial data cleaning steps for further analysis

In [14]:
import pandas as pd

### Load Dataset

In [15]:
df = pd.read_csv('../data/raw/DataScientist.csv')

In [16]:
df.head()

,Unnamed: 0,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply
0,0,0,Senior Data Scientist,$111K-$181K (Glassdoor est.),"ABOUT HOPPER\n\nAt Hopper, we’re on a mission ...",3.5,Hopper\n3.5,"New York, NY","Montreal, Canada",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable,-1,-1
1,1,1,"Data Scientist, Product Analytics",$111K-$181K (Glassdoor est.),"At Noom, we use scientifically proven methods ...",4.5,Noom US\n4.5,"New York, NY","New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable,-1,-1
2,2,2,Data Science Manager,$111K-$181K (Glassdoor est.),Decode_M\n\nhttps://www.decode-m.com/\n\nData ...,-1.0,Decode_M,"New York, NY","New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable,-1,True
3,3,3,Data Analyst,$111K-$181K (Glassdoor est.),Sapphire Digital seeks a dynamic and driven mi...,3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ","Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,"Zocdoc, Healthgrades",-1
4,4,4,"Director, Data Science",$111K-$181K (Glassdoor est.),"Director, Data Science - (200537)\nDescription...",3.4,United Entertainment Group\n3.4,"New York, NY","New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"BBDO, Grey Group, Droga5",-1

### Dataset Overview

The first step is to examine the overall dimensions of the dataset and understand the available information.

In [17]:
df.shape

(3909, 17)

The dataset contains 3909 job postings and 17 features.

In [18]:
df.columns

Index(['Unnamed: 0', 'index', 'Job Title', 'Salary Estimate',
       'Job Description', 'Rating', 'Company Name', 'Location', 'Headquarters',
       'Size', 'Founded', 'Type of ownership', 'Industry', 'Sector', 'Revenue',
       'Competitors', 'Easy Apply'],
      dtype='str')

The dataset includes information about job titles, salary estimates, company characteristics, location, industry information and job description.

### Data Types

Understanding data types is necessary before performing data cleaning and analysis.

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3909 entries, 0 to 3908
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         3909 non-null   int64
 1   index              3909 non-null   int64
 2   Job Title          3909 non-null   str
 3   Salary Estimate    3909 non-null   str
 4   Job Description    3909 non-null   str
 5   Rating             3909 non-null   float64
 6   Company Name       3909 non-null   str
 7   Location           3909 non-null   str
 8   Headquarters       3909 non-null   str
 9   Size               3909 non-null   str
 10  Founded            3909 non-null   int64
 11  Type of ownership  3909 non-null   str
 12  Industry           3909 non-null   str
 13  Sector             3909 non-null   str
 14  Revenue            3909 non-null   str
 15  Competitors        3909 non-null   str
 16  Easy Apply         3909 non-null   str
dtypes: float64(1), int64(3), str(13)
memory usage: 519.3 KB

### Missing and Duplicated Values Check

Missing and duplicated values can affect analysis quality. Therefore, the dataset must be checked for incomplete or duplicated reccords.

In [20]:
df.isna().sum()

Unnamed: 0           0
index                0
Job Title            0
Salary Estimate      0
Job Description      0
Rating               0
Company Name         0
Location             0
Headquarters         0
Size                 0
Founded              0
Type of ownership    0
Industry             0
Sector               0
Revenue              0
Competitors          0
Easy Apply           0
dtype: int64

In [21]:
str_columns = df.select_dtypes('str').columns
for col in str_columns:
    boolean_df = df[col].str.strip() == ""
    if boolean_df[1]:
        print('Empty String Found')

In [22]:
df.duplicated().sum()

np.int64(0)

No missing or duplicated values are found.

### Descriptive Statistics

Descriptive statistics provide an overview of measures such as count, mean, standard deviation, minimum and maximum values for numerical feature.

And for non-numeric features it provides measures such as count, number of unique values, most frequent value and the frequency of the most frequent value.

In [23]:
df.describe()

        Unnamed: 0        index       Rating      Founded
count  3909.000000  3909.000000  3909.000000  3909.000000
mean   1954.000000  2167.446662     3.283576  1479.154771
std    1128.575429  1247.657849     1.575749   855.750138
min       0.000000     0.000000    -1.000000    -1.000000
25%     977.000000  1121.000000     3.200000  1625.000000
50%    1954.000000  2161.000000     3.700000  1976.000000
75%    2931.000000  3249.000000     4.100000  2002.000000
max    3908.000000  4379.000000     5.000000  2020.000000

In [24]:
(df == -1).sum()

Unnamed: 0             0
index                  0
Job Title              0
Salary Estimate        0
Job Description        0
Rating               409
Company Name           0
Location               0
Headquarters           0
Size                   0
Founded              977
Type of ownership      0
Industry               0
Sector                 0
Revenue                0
Competitors            0
Easy Apply             0
dtype: int64

- `Unnamed:0` and `index` features do not contain any meaningful value for analysis therefore they will be removed.
- For some numerical features a minimum value of -1 is recorded. It most likely means that it is a missing value. Even though this dataset doesn't include standard missing values it may have hidden missing values.

In [25]:
df.describe(include='str')

,Job Title,Salary Estimate,Job Description,Company Name,Location,Headquarters,Size,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply
count,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909
unique,2079,148,3685,2075,191,543,9,15,96,26,14,422,2
top,Data Scientist,$93K-$151K (Glassdoor est.),The U.S. Department of the Treasury has a dist...,Apple\n4.1,"Austin, TX","New York, NY",10000+ employees,Company - Private,-1,Information Technology,Unknown / Non-Applicable,-1,-1
freq,274,62,14,60,345,297,993,1933,546,1124,1163,2760,3745

In [26]:
(df == '-1').sum()

Unnamed: 0              0
index                   0
Job Title               0
Salary Estimate         0
Job Description         0
Rating                  0
Company Name            0
Location                0
Headquarters          240
Size                  229
Founded                 0
Type of ownership     229
Industry              546
Sector                546
Revenue               229
Competitors          2760
Easy Apply           3745
dtype: int64

Some features have the value -1. It may represent unavailable information.

`Salary Estimate` is stored as text and should be converted before salary analysis.

# Conclusion

The initial exploration provided a comprehensive understanding of the dataset structure and quality.

**Key findings:**

* The dataset contains **3,909 job postings** and **17 features** related to data science careers.
* No explicit missing values or duplicate records were identified.
* Several features use **`-1` as a placeholder value** instead of standard missing values. This was observed in `Rating`, `Founded`, `Industry`, `Competitors`, and `Easy Apply`.
* The `Competitors` and `Easy Apply` features contain a high proportion of placeholder values, which may limit their usefulness for further analysis.
* The `Job Title` feature contains many unique and highly specific job titles, indicating that role standardization may be beneficial for role-based analysis.
* The `Salary Estimate` feature is stored as text and will require preprocessing before salary analysis can be performed.

**Next Steps (Data Cleaning):**

* Remove unnecessary index columns (`Unnamed: 0` and `index`).
* Replace placeholder values (`-1`) with `NaN` where appropriate.
* Evaluate whether features with a high percentage of unavailable information should be retained or removed.
* Clean and transform the `Salary Estimate` feature into numerical variables.
* Standardize job titles by creating broader job categories while preserving the original titles.
* Save the cleaned dataset for subsequent exploratory data analysis.